# Socket
bind 127.0.0.1
port 6969

# Logfile path
# Requires sudo when using a file not owned by user
logfile /var/log/ramora/ramora.log

# Hashmap
max_load_factor 0.7
migrating_load 4
initial_hmap_cap 131072

# Memory
initial_heap_cap 2048
initial_buffer_cap 16384
max_buffer_cap 16777216

# Networking
max_payload_size 4096
max_pooled_conn_count 128
idle_timeout_ms 60000
# Set idle_timeout_ms <= 0 to disable idle timeout

# Event loop
read_chunk 8192
max_events 2048
